server:
  port: 8080
spring:
  application:
    name: oem
  # MySQL
  datasource:
    url: jdbc:mysql://192.168.21.251:3306/xhd?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ssadmin
    password: Sss!@#2018
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #阿里druid连接池驱动配置信息
    druid:
      #初始化大小，最小，最大
      initial-size: 1
      min-idle: 10
      max-active: 100
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      #通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      max-open-prepared-statements: 100
  # REDIS
  redis:
    host: 127.0.0.1 # server host
    port: 6379 # connection port
    database: 1 # database name
    password: wangcm # server password
    #    timeout: 2000
    # 默认缓存过期时间（秒）
    expireSeconds: 3600
    pool:
  #      max-idle: 8
  #      min-idle: 0
  #      max-active: 8
  #      max-wait: -1
  # Logback
  log:
    file:
      path: logs/${spring.application.name}/${spring.profiles.active} # 日志文件路径
      #path: logs/${spring.application.name}/${spring.profiles.active} # 日志文件路径
      maxKeep: 5  # 最大保留的文件个数
## mybatis configuration
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.sss.oem.domain.entity

